### ISSUE TITLE
BasicPublisher下对rabbitTemplate的配置，有两项必须设置它的子类下

### ISSUE THREAD

**Issue by liumapp** [lemon-china/lemon-rabbitmq#1]
BasicPublisher下对rabbitTemplate的配置，有两项必须设置它的子类下：

rabbitTemplate.setReturnCallback(this);
rabbitTemplate.setConfirmCallback(this);

如果直接设置在sendMessage下，那么在继承了BasicPublisher的子类有多个的情况下，将会触发onMessage的InvocationTargetException异常

亲测如此
PR就懒得提交了...

**Comment by liumapp** [comment]
setConfirmCallback可以不用填写，是我自己测试的时候加上的，

**Comment by lonyee1989** [comment]
rabbitTemplate.setReturnCallback(this);
rabbitTemplate.setConfirmCallback(this);
根据您的提议，实测callback只能全局单例使用，这块内容已经做了一个改进版本，后续调整本示例代码

可参考新cloud服务内改进
https://github.com/lemon-china/lemon-consul-cloud
